cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

mexican/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls")),
    path("", include("pages.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

pages/urls.py
from django.urls import path

from .views import AboutPageView, HomePageView, ContactInfo

app_name = "pages"

urlpatterns = [
    path("about/", AboutPageView.as_view(), name="about"),
    path("contact/", ContactInfo, name="contact"),
    path("", HomePageView.as_view(), name="home"),
]

products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
]

orders/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from localflavor.br.models import BRCPFField, BRPostalCodeField, BRStateField
from model_utils.models import TimeStampedModel

from products.models import Product


class Order(TimeStampedModel):
    cpf = BRCPFField("CPF")
    name = models.CharField("Nome Completo", max_length=250)
    email = models.EmailField()
    postal_code = BRPostalCodeField("CEP")
    address = models.CharField("Endereço", max_length=250)
    number = models.CharField("Número", max_length=250)
    complement = models.CharField("Complemento", max_length=250, blank=True)
    district = models.CharField("Bairro", max_length=250)
    state = BRStateField("Estado")
    city = models.CharField("Cidade", max_length=250)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Pedido {self.id}"

    def get_total_price(self):
        total_cost = sum(item.get_total_price() for item in self.items.all())
        return total_cost

    def get_description(self):
        return ", ".join(
            [f"{item.quantity}x {item.product.name}" for item in self.items.all()]
        )


class Item(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(settings.CART_ITEM_MAX_QUANTITY),
        ]
    )

    def __str__(self):
        return str(self.id)

    def get_total_price(self):
        return self.price * self.quantity

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block title %}El Taco - Sobre{% endblock title %}

{% block content %}

<div class="container my-3">
  <h1 class="font-weight-bold">Sobre nós</h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, totam iure numquam quaerat amet, officiis
    accusantium dolor assumenda dolores esse dignissimos voluptatem. Commodi laborum non minima dolor illum
    reiciendis est.Temporibus delectus quam odit voluptatibus debitis nesciunt optio voluptates ut inventore porro
    perferendis, quidem magnam repellat quo ratione, quos quod? Nesciunt, in quidem. Necessitatibus sapiente ad iure
    impedit quod cumque?
  </p>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur laborum nam aliquid nostrum a omnis temporibus
    deserunt fugit similique quod? Aliquam, eius quos quam laudantium ea deserunt consectetur magnam
    soluta.Accusamus enim fugit voluptatem, quasi, labore tempora adipisci magni ea voluptatum culpa recusandae qui
    reiciendis maiores ratione animi velit corrupti sequi ab eum placeat. Voluptatem quaerat nesciunt reiciendis
    aperiam vero.
  </p>
  <h3>Nossa localização</h3>
  <p><span style="font-weight: bold">Endereço: </span>R. Augusta, 1474 - Consolação, São Paulo - SP, 01304-001</p>
  <div class="container my-3">
    <div id="map" style="height:400px"></div>
  </div>
</div>
{% block scripts %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC72IhvcHlVEGt1tvDLgW-4iM7WGF-NTQ4&callback=initMap&v=weekly" async defer></script>
<script src="{% static 'js/about-google-maps.js' %}"></script>
{% endblock scripts %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">

{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>{% block title %}El Taco - Home{% endblock title %}</title>
</head>

<body class="d-flex flex-column min-vh-100">

  <nav class="navbar navbar-expand-sm py-3 border-bottom navbar-light">
    <div class="container">
      <a href="{% url 'pages:home' %}" class="navbar-brand">
        <span class="font-weight-bold h3">El Taco | Mexican Food</span>
      </a>

      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"> </span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'products:list' %}" class="nav-link lead mr-4 font-weight-bold">Cardápio</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'pages:about' %}" class="nav-link lead mr-4 font-weight-bold">Sobre Nós</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'pages:contact' %}" class="nav-link lead mr-4 font-weight-bold">Fale Conosco</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'cart:detail' %}" class="nav-link lead mr-4 font-weight-bold">Meu Carrinho</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
  </script>
  {% block script %}
  {% endblock script %}
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <!-- Footer -->
  <footer class="text-center text-lg-start text-white" style="background-color: #45526e">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              El Taco | Mexican Food
            </h6>
            <p>
              Mussum Ipsum, cacilds vidis litro abertis.
              Quem num gosta di mim que vai caçá sua turmis!
              Aenean aliquam molestie leo, vitae iaculis nisl.
              Viva Forevis aptent taciti sociosqu ad litora torquent.
              Posuere libero varius. Nullam a nisl ut ante blandit
              hendrerit. Aenean sit amet nisi.
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Nosso contato!</h6>
            <p><i class="fas fa-home mr-3"></i> R. Augusta, 1474 - Consolação, São Paulo - SP, 01304-001</p>
            <p><i class="fas fa-envelope mr-3"></i> eltaquito@mexicanfood.com.br</p>
            <p><i class="fas fa-phone mr-3"></i> +55 11 2456-1234</p>
            <p><i class="fas fa-print mr-3"></i> +55 11 98765-4567</p>
          </div>
          <!-- Grid column -->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-3">

      <!-- Section: Copyright -->
      <section class="p-3 pt-0">
        <!-- Grid column -->
        <div class="col-lg-12 text-center">
          <!-- Copyright -->
          <div class="p-3">
            © 2021 Todos os direitos reservados:
            <a class="text-white" href="https://mdbootstrap.com/">
              <p>eltacomexicanfood.com.br</p>
            </a>
          </div>
          <!-- Copyright -->
        </div>
        <!-- Grid column -->
      </section>
      <!-- Section: Copyright -->
    </div>
    <!-- Grid container -->
  </footer>
  <!-- Footer -->

</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block title %}El Taco - Fale Conosco{% endblock title %}

{% block content %}

<div class="container my-3">
  <h3 class="font-weight-bold">Fale Conosco!</h3>
  <div class="col-lg-6 mx-auto">
    <form action="." method="POST">
      {% csrf_token %}
      <fieldset class="border-bottom mb-3 ">
        <div id="div_id_name" class="form-group">
          <label for="id_name" class=" requiredField">
            Nome Completo<span class="asteriskField">*</span>
          </label>
          <div class="">
            <input type="text" name="full-name" maxlength="250" class="textinput textInput form-control" required=""
              id="id_name">
          </div>
        </div>
        <div id="div_id_email" class="form-group">
          <label for="id_email" class=" requiredField">
            Email<span class="asteriskField">*</span>
          </label>
          <div class="">
            <input type="email" name="email" maxlength="254" class="emailinput form-control" required="" id="id_email">
          </div>
        </div>
        <div id="div_id_subject" class="form-group">
          <label for="id_subject" class=" requiredField">
            Assunto<span class="asteriskField">*</span>
          </label>
          <div class="">
            <input type="text" name="subject" maxlength="250" class="textinput textInput form-control" required=""
              id="id_subject">
          </div>
        </div>
        <div id="div_id_subject" class="form-group">
          <label for="id_subject" class=" requiredField">
            Digite sua mensagem<span class="asteriskField">*</span>
          </label>
          <div class="">
            <textarea name="message" id="message" cols="30" rows="5" class="textinput textInput form-control"></textarea>
          </div>
        </div>
      </fieldset>
      <div class="form-group">
        <div class="">
          <input type="Submit" value="Enviar" class="btn btn-primary btn btn-success btn-lg btn-block">
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Olá!</h1>
    <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur autem beatae saepe at nulla accusamus,
        mollitia quibusdam laborum, voluptatem corporis molestiae ipsa, id quasi distinctio deserunt et. Ipsam, dolorem
        quidem.Itaque, magnam explicabo! Corrupti eos optio repellat debitis omnis voluptates laudantium fuga dolore
        incidunt autem. Veritatis harum sunt eveniet sequi, impedit quaerat modi assumenda recusandae molestias adipisci
        laborum cumque ad.
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non porro temporibus, unde pariatur sit
        doloremque molestiae fugit, nostrum, atque beatae praesentium vero deserunt aspernatur cumque culpa reiciendis
        corrupti dolores!Illum ratione enim repellendus quas? Inventore at aut aliquid minus pariatur facilis id
        adipisci consequuntur soluta doloremque. Sit quae quisquam quis molestiae similique esse natus atque saepe rem
        placeat? Nostrum?
    </p>
</div>

{% endblock content %}

templates/order_summary.html
<div class="card border-0 bg-light p-4">
    <h4>Resumo do Pedido</h4>
    <ul class="list-group list-group-flush">
        {% for item in items %}
        <li class="list-group-item bg-light">
            {{ item.quantity }}x {{ item.product.name }}
            <span class="float-right">R$ {{ item.total_price }}{{ item.get_total_price }}</span>
        </li>
        {% endfor %}
        <li class="font-weight-bold list-group-item bg-light">Total
            <span class="float-right">R$ {{ total_price }}</span>
        </li>
    </ul>
</div>

templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if page.has_previous %}
    <li class="page-item">
    <a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
      </li>
    {% endif %}
    {% if page.number|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ page.number|add:'-5' }}">&hellip;</a></li>
        {% endif %}

        {% for i in page.paginator.page_range %}
            {% if page.number == i %}
                <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(Atual)</span>
              </span>
            </li>
            {% elif i > page.number|add:'-5' and i < page.number|add:'5' %}
                 <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page.paginator.num_pages > movies.number|add:'4' %}
           <li class="page-item"><a class="page-link" href="?page={{ page.number|add:'5' }}">&hellip;</a></li>
        {% endif %}

    {% if page.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Próximo</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Próximo</a>
      </li>
    {% endif %}
  </ul>
</nav>